### PR TITLE
[#435] 인터셉터 등록 기능을 어노테이션화 한다.

### LINKED ISSUE #435: [refactor/auth_interceptor_register] 인터셉터 등록 기능을 어노테이션화 한다.
## 작업 내용

기존, 로그인 또는 게스트에 대한 인증을 위한 인터셉터 로직을 어노테이션화 시킨다.
<br/>

### PR DESCRIPTION
**Pull request by bperhaps**
## 상세 내용

이제 진짜 됨. 서버에 올려서 돌아가는 확인하고 올림 
<br/>

## 기타

<br/>

Close #435

### CODE REVIEW

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT BUILDER</b> 💪😇<br/><br/>Build and Test failure

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT BUILDER</b> 💪😇<br/><br/>Build and Test failure

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT BUILDER</b> 💪😇<br/><br/>Build and Test failure

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT BUILDER</b> 💪😇<br/><br/>Build and Test failure

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT BUILDER</b> 💪😇<br/><br/>Build and Test failure

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Pipeline aborted due to quality gate failure - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Pipeline aborted due to quality gate failure - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Pipeline aborted due to quality gate failure - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Pipeline aborted due to quality gate failure - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Cool! All passes! - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

**Review by da-nyee — APPROVED** [review]
너잘의 P;ㅠ ,,, 수고하셨습니다 👍

**Pull request merged**
