### PR TITLE
[#506] User - Portfolio 연관관계 매핑 추가

### LINKED ISSUE #506: [fix/portfolio] User - Portfolio 연관관계 매핑을 추가한다.
## 상세 내용
- User - Portfolio 연관관계 매핑 추가

### PR DESCRIPTION
**Pull request by da-nyee**
## 상세 내용
- User - Portfolio 연관관계 매핑 빠진 부분을 추가했습니다.

<br/>

Close #506

### CODE REVIEW

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT BUILDER</b> 💪😇<br/><br/>Test failure

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT BUILDER</b> 💪😇<br/><br/>Test failure

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Cool! All passes! - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

**Review by binghe819 — APPROVED** [review]
굳굳!

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Cool! All passes! - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

**Pull request merged**
