### PR TITLE
[#419] JaCoCo 추가

### LINKED ISSUE #419: [chore/jacoco] JaCoCo를 추가한다.
## 작업 내용
- build.gradle에 JaCoCo 플러그인 추가

### PR DESCRIPTION
**Pull request by da-nyee**
## 상세 내용
- build.gradle에 JaCoCo 플러그인을 추가했습니다.

<br/>

### task 실행 순서
- test -> jacocoTestReport -> jacocoTestCoverageVerification

<br/>

### jacocoTestCoverageVerification 설명
```groovy
violationRules {
    // 룰 설정
    rule {
        // 룰을 클래스 단위로 체크
	element = 'CLASS'

        // 메소드 커버리지를 최소 65% 만족해야 함
	limit {
            counter = 'METHOD'
            value = 'COVEREDRATIO'
            minimum = 0.65
	}

        // 커버리지 체크에서 제외하는 클래스들
	excludes = [
                '**.*RestTemplate*',
                '**.*PickGitApplication*',
                '**.*Dto*',
                '**.*Requester*',
                '**.*Request*',
                '**.*Response*',
                '**.*OAuthClient*',
                '**.*Exception*',
                '**.*Storage*',
                '**.*Interceptor*'
	]
    }
}
```

<br/>

### 참고 자료
- [Gradle 프로젝트에 JaCoCo 설정하기](https://techblog.woowahan.com/2661/)

<br/>

Close #419

### CODE REVIEW

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Pipeline aborted due to quality gate failure - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Pipeline aborted due to quality gate failure - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

**Review by bperhaps — COMMENTED** [review]
💪😇 <b>PICK-GIT SONARQUBE</b> 💪😇<br/><br/>Cool! All passes! - [Read the report here!](http://52.78.17.123:9000/dashboard?id=pick-git-sonarqube)

**Review by binghe819 — APPROVED** [review]
다니 고생 많았어ㅠㅠㅠ

코코가 힘들게 하네...

**Pull request merged**
